global using WarehouseManagmentSystemAPI.Infrastructure.OrderEntityRoot;
global using WarehouseManagmentSystemAPI.Infrastructure.Entities;
global using WarehouseManagmentSystemAPI.Infrastructure.Entities.OrderEntityRoot;
global using System.ComponentModel.DataAnnotations.Schema;